### ISSUE TITLE
Bug Report: Not working Ubuntu running Chrome?

### ISSUE THREAD

**Issue by aeksco** [aeksco/pantograph_cv#5]

**Comment by aeksco** [comment]
Error message THREE.WebGLRenderer 73
vendor.js:21129 Unhandled rejection TypeError: view.append is not a function
   at RenderView.onRender (http://aeks.co/pantograph_alpha/js/app.js:1426:17)
   at Object._triggerMethod (http://aeks.co/pantograph_alpha/js/vendor.js:15595:25)
   at RenderView.triggerMethod (http://aeks.co/pantograph_alpha/js/vendor.js:16849:28)
   at RenderView.render (http://aeks.co/pantograph_alpha/js/vendor.js:16999:12)
   at RenderView.render (http://aeks.co/pantograph_alpha/js/vendor.js:18005:51)
   at constructor._renderView (http://aeks.co/pantograph_alpha/js/vendor.js:16125:12)
   at constructor.show (http://aeks.co/pantograph_alpha/js/vendor.js:16055:14)
   at LayoutView.onRender (http://aeks.co/pantograph_alpha/js/app.js:1175:23)
   at Object._triggerMethod (http://aeks.co/pantograph_alpha/js/vendor.js:15595:25)
   at LayoutView.triggerMethod (http://aeks.co/pantograph_alpha/js/vendor.js:16849:28)
   at LayoutView.render (http://aeks.co/pantograph_alpha/js/vendor.js:16999:12)
   at LayoutView.render (http://aeks.co/pantograph_alpha/js/vendor.js:18005:51)
   at constructor._renderView (http://aeks.co/pantograph_alpha/js/vendor.js:16125:12)
   at constructor.show (http://aeks.co/pantograph_alpha/js/vendor.js:16055:14)
   at SwapView.swap (http://aeks.co/pantograph_alpha/js/app.js:145:14)
   at SwapRegion.<anonymous> (http://aeks.co/pantograph_alpha/js/app.js:177:31)
vendor.js:54360 THREE.WebGLProgram: gl.getProgramInfoLog()
scene.coffee:97ON WINDOW RESIZE

vendor.js:49555 THREE.WebGLRenderer 73
vendor.js:21129 Unhandled rejection TypeError: view.append is not a function
   at RenderView.onRender (http://aeks.co/pantograph_alpha/js/app.js:1426:17)
   at Object._triggerMethod (http://aeks.co/pantograph_alpha/js/vendor.js:15595:25)
   at RenderView.triggerMethod (http://aeks.co/pantograph_alpha/js/vendor.js:16849:28)
   at RenderView.render (http://aeks.co/pantograph_alpha/js/vendor.js:16999:12)
   at RenderView.render (http://aeks.co/pantograph_alpha/js/vendor.js:18005:51)
   at constructor._renderView (http://aeks.co/pantograph_alpha/js/vendor.js:16125:12)
   at constructor.show (http://aeks.co/pantograph_alpha/js/vendor.js:16055:14)
   at LayoutView.onRender (http://aeks.co/pantograph_alpha/js/app.js:1175:23)
   at Object._triggerMethod (http://aeks.co/pantograph_alpha/js/vendor.js:15595:25)
   at LayoutView.triggerMethod (http://aeks.co/pantograph_alpha/js/vendor.js:16849:28)
   at LayoutView.render (http://aeks.co/pantograph_alpha/js/vendor.js:16999:12)
   at LayoutView.render (http://aeks.co/pantograph_alpha/js/vendor.js:18005:51)
   at constructor._renderView (http://aeks.co/pantograph_alpha/js/vendor.js:16125:12)
   at constructor.show (http://aeks.co/pantograph_alpha/js/vendor.js:16055:14)
   at SwapView.swap (http://aeks.co/pantograph_alpha/js/app.js:145:14)
   at SwapRegion.<anonymous> (http://aeks.co/pantograph_alpha/js/app.js:177:31)

**Comment by aeksco** [comment]
SwapRegion has been dropped so this issue should be resolved - closing.
